jobs:
  include:
    - stage: "Build"
      script: .travis/build.sh 
      if: branch = develop
    - stage: "Test"
      if: branch =~ /(feature\/.*|ops\/.*|develop)/
      script: .travis/tests.sh
    - stage: "Deploy"
      if: branch = develop
      script: ".travis/Deploy.sh"